version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: orders
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    image: ll/orders-app
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: orders_user
      DATABASE_PASS: 123456
    links:
      - db
